spring:
  application:
    name: systeme-annonce
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: XXX!
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

api:
  security:
    jwt:
      secret: MzRkYjU2Y2M4OWIxY2RiM2EyZGFmNWYxODkxNzI1NDRkYmFmZmE2ZmNmZGFhMjEzOGI4NmFmMTM2Mzg5NjQ5NA==
      expiration-time: 86400000

server:
  port: 8080